language: csharp
solution: NBIoT/NBIoT.sln
os:
  - linux
  - osx
dist: xenial
sudo: yes
mono: none
dotnet: 2.2.102
install:
  - dotnet restore NBIoT
script:
  - dotnet build NBIoT
  - dotnet test NBIoT/Tests/Tests.csproj
